name: nielsen_flutter_plugin
description: A common plugin interface for the Nielsen AppSDK Flutter Plugin.
version: 10.1.0+0
publish_to: none

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    platforms:
      android:
        default_package: nielsen_flutter_plugin_android
      ios:
        default_package: nielsen_flutter_plugin_ios

dependencies:
  flutter:
    sdk: flutter
  nielsen_flutter_plugin_android:
    path: ../nielsen_flutter_plugin_android
  nielsen_flutter_plugin_ios:
    path: ../nielsen_flutter_plugin_ios
  nielsen_flutter_plugin_platform_interface:
    path: ../nielsen_flutter_plugin_platform_interface
